openapi: 3.0.1
info:
  version: 1.1.0
  title: appNG Scheduler REST API
  description: The REST API for appNG Scheduler
  contact:
    name: appNG developer team
    email: matthias.mueller@appng.org
    url: https://github.com/appNG/appng-scheduler
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
paths:
  "/jobState/{application}/{job}":
    get:
      tags:
        - JobState
      operationId: getJobState
      parameters:
        - in: path 
          name: application
          description: name of the application
          required: true  
          schema:
            type: string
        - in: path 
          name: job
          description: name of the job
          required: true         
          schema:
            type: string
        - in: query 
          name: pageSize
          description: size of the page
          required: false
          schema:
            type: integer
            default: 10
        - in: query 
          name: records
          description: show records?
          required: false
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: the job's state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobState" 
  "/jobState/list":
    get:
      tags:
        - JobState
      operationId: getJobs
      parameters:
       - in: query 
         name: jobdata
         description: show jobdata?
         required: false
         schema:
           type: boolean
           default: false
       - in: query 
         name: all
         description: show jobs from all sites?
         required: false
         schema:
           type: boolean
           default: false
       - in: query
         name: thresholds
         description: job has some thresholds defined?
         required: false
         schema:
           type: boolean
      responses:
        "200":
          description: a list of jobs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      name: Authorization
      bearerFormat: uuid
  schemas:
    job:
      type: object    
      properties:
        _self:
          type: string
          description: path to details  
        site: 
          type: string
          description: name of the site
        application:
          type: string
          description: name of the application
        job:
          type: string
          description: name of the job
        thresholdsPresent:
          type: boolean
          description: are there any treshOlds defined for thos job?
        jobData:
          type: object
          additionalProperties:
            type: object
    jobs:
      type: object 
      properties:
        jobs:
          type: array
          items:
            $ref: "#/components/schemas/job"
    jobState:
      type: object    
      properties:
        site:
          type: string
          description: name of the site
        application:
          type: string
          description: name of the application
        job:
          type: string
          description: name of the job
        totalRecords:
          type: integer
          description: total number of records
        state:
            type: string
            enum: [OK, WARN, ERROR, UNDEFINED]
        startedAfter:
          type: string
          format: date-time
          description: the date after that the records started
        jobData:
          type: object
          additionalProperties:
            type: object
        records:
          type: array
          items:
            $ref: "#/components/schemas/jobRecord"
    jobRecord:
      type: object
      properties:
        id:
          type: integer
          description: the ID
        start:
          type: string
          format: date-time
          description: start date
        end:
          type: string
          format: date-time
          description: end date
        duration:
          type: integer
          description: duration in milliseconds
        runOnce:
          type: boolean
          description: run once flag
        stacktrace:
          type: string
          description: the stacktrace
        state:
            type: string
            enum: [OK, ERROR]
  